version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - python -m venv .venv
      - . .venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install -r requirements.test.txt
      - rm -rf test-reports
      - mkdir test-reports
  build:
    commands:
      - pytest --html=test-reports/report.html --self-contained-html -s -v --cov=. --cov-report=html:test-reports/coverage --junitxml=test-reports/junit.xml --log-file=test-reports/logs.txt test
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  coverage:
    files:
      - "coverage/*"
    base-directory: 'test-reports'
    discard-paths: yes
  report:
    files:
      - 'junit.xml'
      - 'report.html'
      - 'assets/*'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml